language: node_js
os: linux
sudo: required
dist: trusty
env:
  global:
    - GOOGLE_CHROME_BINARY="/usr/bin/google-chrome-beta"
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
node_js:
  - '10'
  - '12'
install:
  - yarn bootstrap
script:
  - npm run test ci
after_success:
  - if [[ `node -v` == *"v12"* ]]; then (cat coverage/lcov.info | coveralls); fi
